import { ChangeDetectorRef, ElementRef, EventEmitter, Renderer2 } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { Homeworks } from '../../core/homeworks';
export declare class WorksToggle extends Homeworks implements ControlValueAccessor {
    protected renderer: Renderer2;
    private changeDetectorRef;
    private elementRef;
    private $element;
    private $toggle;
    private propagateChange;
    private propagateTouch;
    private m_model;
    private m_disabled;
    private m_checked;
    private m_readonly;
    private m_required;
    private m_placeholder;
    private m_color;
    toggleChild: ElementRef;
    model: any;
    placeholder: any;
    color: string;
    class: string;
    type: string;
    id: string;
    name: string;
    title: string;
    checked: any;
    disabled: any;
    readonly: any;
    required: any;
    value: any;
    onUpdate: EventEmitter<any>;
    constructor(renderer: Renderer2, changeDetectorRef: ChangeDetectorRef, elementRef: ElementRef);
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    render(): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
}
